### ISSUE TITLE
installvrm.m

### ISSUE THREAD

**Issue by YifanQie** [sumitsinha/Deep_Learning_for_Manufacturing#4]
Hi sumitsinha,

 I found there might be something wrong with the file installvrm.m.
 The file "(3) KINEMATICS (src)" is missing in the folder _caesimulations_. 
 Maybe I understand it in the wrong way.  But could you please have a look at the file to ensure the file is working?

Thank you in advance!

best

**Comment by sumitsinha** [comment]
Hello YifanQie,

Thank you for this. Apologies for this Kinematics is not required for CAE simulations and hence has not been included. The same has been removed from installation installvrm.m file in the latest commit.

Thanks
